version: '3.3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    container_name: foodgram_db
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    container_name: foodgram_back
    build: ./backend
    env_file: .env
    volumes:
      - static:/backend_static
      - media:/app/media/
    depends_on:
      - db

  frontend:
    container_name: foodgram_front
    build: ./frontend
    command: cp -r /app/build/. /frontend_static/
    env_file: .env
    volumes:
      - static:/frontend_static

  nginx:
    container_name: nginx
    build: ./nginx
    env_file: .env
    ports:
      - "8000:80"
    volumes:
      - ./docs/:/usr/share/nginx/html/api/docs/
      - static:/static/
      - media:/media/
    depends_on:
      - backend
